### ISSUE TITLE
error while running porder for the firrst time

### ISSUE THREAD

**Issue by pmlefeuvre** [samapriya/porder#17]
Hei,

I have just installed porder on Mac OSX 10.13.6 with python3.6 but get the error below when running it. Does anyone with more experience know how to fix this?
Thanks for your help,

$ porder
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/porder", line 7, in <module>
    from porder.porder import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/porder/porder.py", line 5, in <module>
    from geojson2id import idl
ModuleNotFoundError: No module named 'geojson2id'

**Comment by samapriya** [comment]
Hi @pmlefeuvre 
Can you tell me about how you installed porder? I am running porder on Python 3.6 without any issues

**Comment by samapriya** [comment]
Closing this issue because of inactivity
