### ISSUE TITLE
Python 3 incompatibility: CSV is parsed as a string but csv package expects bytes object

### ISSUE THREAD

**Issue by rbavery** [samapriya/porder#8]
```
(v2-cloud)~/cloud-free-planet/notebooks$ porder idlist --input "/home/rave/cloud-free-planet/notebooks/test_tile_half.geojson" --start "2018-07-01" --end "2018-07-31" --item "PSScene4Band" --asset "analytic_sr" --number 10000 --outfile "/home/rave/cloud-free-planet/notebooks/test_half_ids.csv" --cmin 0 --cmax 1 --overlap 0
Traceback (most recent call last):
  File "/home/rave/anaconda3/bin/porder", line 11, in <module>
    sys.exit(main())
  File "/home/rave/anaconda3/lib/python3.6/site-packages/porder/porder.py", line 172, in main
    args.func(args)
  File "/home/rave/anaconda3/lib/python3.6/site-packages/porder/porder.py", line 55, in idlist_from_parser
    outfile=args.outfile)
  File "/home/rave/anaconda3/lib/python3.6/site-packages/porder/geojson2id.py", line 118, in idl
    writer.writeheader()
  File "/home/rave/anaconda3/lib/python3.6/csv.py", line 144, in writeheader
    self.writerow(header)
  File "/home/rave/anaconda3/lib/python3.6/csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
TypeError: a bytes-like object is required, not 'str'
```

Looks like it is related to how python 2 and 3 handle reading and writing csvs: https://stackoverflow.com/questions/34283178/typeerror-a-bytes-like-object-is-required-not-str-in-python-and-csv

It might be a simple fix of changing all the write options from `w` to explicitly be `wb` so that Python 3 interprets `args.outfile` as bytes. Thoughts?

**Comment by samapriya** [comment]
The option is already set to 'w' which is what Python 3 requires instead of wb if you read the solution in the StackOverflow link you provided.

**Comment by Ntkrell** [comment]
@samapriya @rbavery Wait so what was the solution? I get the same error whether I run py 2.7 or 2.6. Where do I change 'wb' to 'w' or vice versa?

**Comment by Ntkrell** [comment]
Ah, found out that the answer is here: https://github.com/samapriya/porder/issues/11.

:)
